### ISSUE TITLE
Small field for username

### ISSUE THREAD

**Issue by EvgeniyPatlan** [adivinho/v0luntario#1]

**Comment by EvgeniyPatlan** [comment]
Hi. I think varchar(20) is not enough let it be at least 32

**Comment by adivinho** [comment]
Ok, it will be changed to 45
Who knows if someone would like to have the login
pneumonoultramicroscopicsilicovolcanoconiosis

**Comment by EvgeniyPatlan** [comment]
as for login email address or concatenation of First and Last Name could be used so it is better to have long filed

**Comment by adivinho** [comment]
changed to VARCHAR(45)
